blog/urls.py
from blog.views import *
from user_auth.views import *
from django.urls import path


urlpatterns = [
    path('contact_form', contact_form, name='contact_form'),
    path('articles', ArticlesListView.as_view(), name='articles'),
    path('article/create', create_article, name='art_create'),
    path('article/<int:id>', ArticleDetailView.as_view(), name='art_detail'),
    path('article/update/<int:id>', ArticleUpdateView.as_view(), name='art_update'),
    path('comments', CommentListView.as_view(), name='comments'),
    path('comment/create/<int:id>', comment_create, name='comment_create'),
    path('users', UserListView.as_view(), name='users'),
    path('user_detailed/<int:id>', UserDetailView.as_view(), name='user_det'),
]

practika/urls.py
from django.contrib.auth.models import User
from django.contrib import admin
from django.urls import include, path

from rest_framework import routers, serializers, viewsets

from blog.views import UserViewSet, GroupViewSet, ArticleViewSet, CommentViewSet

from user_auth.views import *


# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ['url', 'username', 'email', 'is_staff']


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'groups', GroupViewSet)
router.register(r'articles', ArticleViewSet)
router.register(r'comments', CommentViewSet)


urlpatterns = [
    path('', home, name='home'),
    path('', include('blog.urls')),
    path('api/', include(router.urls)),
    path('admin/', admin.site.urls),
    path('accounts/', include('user_auth.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

]

blog/models.py
from django.db import models
from django.conf import settings


class Article(models.Model):
    title = models.CharField(max_length=100, verbose_name='Название статьи', unique=True)
    short_description = models.CharField(max_length=250, verbose_name='Краткое описание')
    text = models.TextField(verbose_name='Текст статьи')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    published = models.BooleanField(default=True, verbose_name='Опубликовано')

    class Meta:
        unique_together = ['title', 'short_description']

    def __str__(self):
        return self.title


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    username = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # username = models.CharField(max_length=250, verbose_name='имя пользователя', default='Guest') # ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True)
    text = models.CharField(max_length=250, verbose_name='Текст комментария')
    is_published = models.BooleanField(default=False, verbose_name='Опубликовано')

    def __str__(self):
        return self.text

blog/views.py
from django.contrib.auth.models import User, Group
from rest_framework import viewsets
from rest_framework import permissions
from blog.serializers import UserSerializer, GroupSerializer, ArticleSerializer, CommentsSerializer


from blog.tasks import *

from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.template.loader import render_to_string
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, ListView, UpdateView
from user_auth.forms import *


def contact_form(request):
    data = dict()
    form = ContactForm()
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            text = form.cleaned_data['text']
            notify_contact.apply_async(kwargs={
                'name': name,
                'email': email,
                'text': text
            })
            data['form_is_valid'] = True
            data['html_form'] = render_to_string('blog/contact_form_success.html')
            return JsonResponse(data)
        else:
            data['form_is_valid'] = False
    context = {'form': form}
    data['html_form'] = render_to_string('blog/contact_form.html', context, request)
    # render_to_string это функция, которая рендерит 'request', при помощи Шаблона, передавая туда 'context'
    return JsonResponse(data)


class ArticlesListView(ListView):
    model = Article
    template_name = 'blog/articles.html'
    queryset = Article.objects.filter(published=True)
    paginate_by = 10


def create_article(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = NewArticle(request.POST)
            if form.is_valid():
                title = form.cleaned_data['title']
                short_description = form.cleaned_data['short_description']
                text = form.cleaned_data['text']
                published = form.cleaned_data['published']
                user = request.user
                a = Article.objects.create(title=title, short_description=short_description,
                                       text=text, author=user, published=published)
                url = f'http://127.0.0.1:8000' + reverse_lazy('art_detail', args=[a.pk])
                notify.apply_async(kwargs={'mas': f'Новая статья: от {user.username}'
                                                  f' {title}, ссылка {url}'})
                return HttpResponseRedirect(reverse('profile'))
        else:
            form = NewArticle()
        return render(request, 'blog/article_create.html', {'form': form})
    return HttpResponseRedirect(reverse('login'))


class ArticleUpdateView(LoginRequiredMixin, UpdateView):
    model = Article
    pk_url_kwarg = 'id'
    template_name = 'blog/article_update.html'
    form_class = NewArticle
    success_url = reverse_lazy('profile')


class ArticleDetailView(DetailView):
    model = Article
    template_name = 'blog/article_detailed.html'
    pk_url_kwarg = 'id'


class UserListView(ListView):
    model = User
    template_name = 'blog/users.html'
    queryset = User.objects.exclude(is_staff=True).all()
    paginate_by = 10


class UserDetailView(DetailView):
    model = User
    template_name = 'blog/user_detailed.html'
    pk_url_kwarg = 'id'


class CommentListView(ListView):
    model = Comment
    template_name = 'blog/comments.html'
    queryset = Comment.objects.filter(is_published=True).all()
    paginate_by = 20


def comment_create(request, id):
    if request.method == 'POST':
        form = NewComment(request.POST)
        article = Article.objects.get(pk=id)
        username = request.user
        if form.is_valid():
            text = form.cleaned_data['text']
            if request.user.is_authenticated:
                email = request.user.email
                url = 'http://127.0.0.1:8000' + reverse_lazy('art_detail', args=[id])
                if email != '':
                    notify_user.apply_async(kwargs={
                        'mas': f'Новый комментарий к статье {article.title}: {text}, {url}',
                        'email': f'{email}'
                    })
                Comment.objects.create(article=article, username=username, text=text)
            else:
                Comment.objects.create(article=article, text=text)
            return HttpResponseRedirect(reverse_lazy('art_detail', args=[id]))
    else:
        form = NewComment()
        article = Article.objects.get(pk=id)
    return render(request, 'blog/comment_create.html', {'form': form, 'article': article})


class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer
    permission_classes = [permissions.IsAuthenticated]


class GroupViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Group.objects.all()
    serializer_class = GroupSerializer
    permission_classes = [permissions.IsAuthenticated]


class ArticleViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = Article.objects.all().order_by('-published')
    serializer_class = ArticleSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]


class CommentViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Comment.objects.all()
    serializer_class = CommentsSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]

templates/blog/article_create.html
{% extends 'base.html' %}

{% block title %}Создать статью{% endblock %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Добавить">
    </form>
{% endblock %}

templates/blog/article_detailed.html
{% extends 'base.html' %}

{% block title %}Про Статью {{  object.title }}{% endblock %}

{% block content %}
    <div>
        <p><a href="{% url 'articles' %}">К списку Статей</a></p>
        <table cellpadding="2" border="1" width="80%">
        <tr>
            <td>Автор:</td>
            <td>{{object.author }}</td>
        </tr>
        <tr>
            <td>Статья:</td>
            <td>{{ object.title }}</td>
        </tr>
        <tr>
            <td>Описание статьи</td>
            <td>{{object.short_description }}</td>
        </tr>
        <tr>
            <td>Текст cтатьи:</td>
            <td>{{object.text }}</td>
        </tr>
        <tr>
            <td>Статус публикации:</td>
            <td>{{object.published }}
            {% if object.author == request.user %}
                <p><a href="{% url 'art_update' id=object.id %}">Редактировать статью</a></p>
            {% endif %}
            </td>
        </tr>
        <td>Комментарии:</td>
        <td>
        {% for comment in object.comment_set.all %}
            <p>
            {% if comment.is_published is True %}

                {% if comment.username is None %}
                    Гость
                    {% else %}
                    {{ comment.username }} написал:
                {% endif %}
                {{ comment.text }}</p>
            {% endif %}
        {% endfor %}
            <p><a href="{% url 'comment_create' id=object.id %}">Добавить комментарий</a></p>
        </td>
        </table>
    </div>
{% endblock %}

templates/blog/article_update.html
{% extends 'base.html' %}

{% block title %}Редактировать статью{% endblock %}

{% block content %}
    <form method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<button class="btn btn-primary" type="submit">Сохранить</button>
	</form>
{% endblock %}

templates/blog/articles.html
{% extends 'base.html' %}

{% block title %}Статьи{% endblock %}
{% block content %}
    <h4> Статьи, мой друг.</h4>
    <div>
        <h2>Статей на странице: {{ object_list.count }}</h2>
        <table border="1", cellspacing="1px" cellpadding="5px">
        <tr style="font-weight: bold">
                <td>id</td>
                <td align="center">Название статьи</td>
                <td align="center">Краткое описание</td>
                <td>Ссылка</td>
                <td>Комментариев</td>
            </tr>
        {% for instance in object_list %}
            {% if instance.published == True %}
            <tr>
                <td>{{ instance.id }}</td>
                <td>{{ instance.title  }}</td>
                <td>{{ instance.short_description  }}</td>
                <td><a href="{% url 'art_detail' id=instance.id %}">подробнее...</a></td>
                <td align="center">{{ instance.comment_set.count }}</td>
            </tr>
            {% endif %}
        {% endfor %}
        </table>
    </div>
    <p></p>
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; первая &laquo;</a>
            <a href="?page={{ page_obj.previous_page_number }}">пред.</a>
        {% endif %}

        <span class="current">
            Страница {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">след.&raquo;</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">последняя &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

templates/blog/comment_create.html
{% extends 'base.html' %}

{% block title %}Добавить комментарий{% endblock %}

{% block content %}

        <p>Название статьи: {{ article.title }}</p>
        <p>Автор: {{ article.author }}</p>
        <p>Текст Статьи: {{ article.text }}</p>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Добавить">
    </form>


{% endblock %}

templates/blog/comments.html
{% extends 'base.html' %}

{% block title %}Все комментарии{% endblock %}

{% block content %}
    {% for comment in object.list %}
        <p>{{ comment.article }}</p>
        <p>{{ comment.username }}</p>
        <p>{{ comment.text }}</p>
    {% endfor %}
{% endblock %}

templates/blog/contact_form.html
 {% block content %}
    <form id="form_s" class="form_s" action="{% url 'contact_form' %}" method="post">
    {% csrf_token %}
        {{ form.as_p}}
    <input id="send" type="submit" value="Отправить">
    </form>
{% endblock %}

templates/blog/contact_form_success.html
{% load static %}

{% block success %}
    <p>Форма отправлена успешно</p>
{% endblock %}

{% block content %}
{% endblock %}

templates/blog/detailed_user.html
{% extends 'base.html' %}

{% block title %}Издатель {{ pk.name }}{% endblock %}

{% block content %}
    <p><a href="{% url 'home' %}">Главная</a></p>
    <p><a href="{% url 'authors' %}">Назад</a></p>
    <p>Автором было написано {{ pk.book_set.all.count }} книг</p>
    <table border="1" cellspacing="1" cellpadding="10">
        <tr>
            <td>Автор</td>
            <td>{{ object.name }}</td>
        </tr>
        <tr>
            <td>Книги</td>
            <td>
                {% for book in object.book_set.all %}
                <p>{{ book }}</p>
                {% endfor %}
            </td>
        </tr>

    </table>

{% endblock %}

templates/blog/user_articles.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/blog/user_detailed.html
{% extends 'base.html' %}

{% block title %}Издатель {{ object.name }}{% endblock %}

{% block content %}
    <p>Автором было написано {{ object.article_set.all.count }} статей</p>
    <table border="1" cellspacing="1" cellpadding="10">
        <tr>
            <td>Автор</td>
            <td>{{ object.username }}</td>
        </tr>
        <tr>
            <td>Статьи</td>
            <td>
                {% for article in object.article_set.all %}
                <p>{{ article }}</p>
                {% endfor %}
            </td>
        </tr>

    </table>

{% endblock %}

templates/blog/user_profile.html
{% extends 'base.html' %}

{% block title %}{% endblock %}

{% block content %}
    <p>Имя пользователя {{ object.username }}</p>
    {% for article in object.article_set.all %}
        <p>Статья: "{{ article.title }}"</p>
    {% endfor %}
{% endblock %}

templates/blog/users.html
{% extends 'base.html' %}

{% block title %}Пользователи{% endblock %}

{% block content %}
    <h5><a href="{% url 'crt_profile' %}">Зарегистрироваться</a></h5>
    <table border="1" cellspacing="1" cellpadding="3">
        <tr>
            <td>ID</td>
            <td>Автор</td>
            <td>Статей</td>
            <td>Ссылка</td>

        </tr>
        {% for instance in object_list %}
            <tr>
                <td>{{ instance.id }}</td>
                <td>{{ instance.username  }}</td>
                <td align="center">{{ instance.comment_set.count  }}</td>
                <td><a href="{% url 'user_det' id=instance.id %}">подробнее</a></td>

            </tr>
        {% endfor %}
    </table>
    <p></p>
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; первая &laquo;</a>
            <a href="?page={{ page_obj.previous_page_number }}">пред.</a>
        {% endif %}

        <span class="current">
            Страница {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">след.&raquo;</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">последняя &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}